/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.CardLayout;

/**
 *
 * @author brian
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ToolBarPanel = new javax.swing.JPanel();
        UnloggedToolbarPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        UnloggedSearchButton = new javax.swing.JButton();
        UnloggedHashButton = new javax.swing.JButton();
        LogInButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        LoggedToolbarPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        LoggedSearch = new javax.swing.JButton();
        LoggedHashButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        MainPane = new javax.swing.JPanel();
        MainPagePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RegPagePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        SignUpButton = new javax.swing.JButton();
        MyPagePanel = new javax.swing.JPanel();
        SearchResultsPanel = new javax.swing.JPanel();
        HashResultsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ToolBarPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToolBarPanel.setLayout(new java.awt.CardLayout());

        jTextField1.setText("jTextField1");

        UnloggedSearchButton.setText("Search");

        UnloggedHashButton.setText("#");

        LogInButton.setText("Log In");

        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UnloggedToolbarPanelLayout = new javax.swing.GroupLayout(UnloggedToolbarPanel);
        UnloggedToolbarPanel.setLayout(UnloggedToolbarPanelLayout);
        UnloggedToolbarPanelLayout.setHorizontalGroup(
            UnloggedToolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UnloggedToolbarPanelLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UnloggedSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UnloggedHashButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(LogInButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegisterButton))
        );
        UnloggedToolbarPanelLayout.setVerticalGroup(
            UnloggedToolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UnloggedToolbarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(UnloggedToolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnloggedSearchButton)
                    .addComponent(UnloggedHashButton)
                    .addComponent(LogInButton)
                    .addComponent(RegisterButton)))
        );

        ToolBarPanel.add(UnloggedToolbarPanel, "card2");

        jTextField2.setText("jTextField2");

        LoggedSearch.setText("Search");

        LoggedHashButton.setText("#");

        LogOutButton.setText("Log out");

        javax.swing.GroupLayout LoggedToolbarPanelLayout = new javax.swing.GroupLayout(LoggedToolbarPanel);
        LoggedToolbarPanel.setLayout(LoggedToolbarPanelLayout);
        LoggedToolbarPanelLayout.setHorizontalGroup(
            LoggedToolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoggedToolbarPanelLayout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoggedSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoggedHashButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(LogOutButton))
        );
        LoggedToolbarPanelLayout.setVerticalGroup(
            LoggedToolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoggedToolbarPanelLayout.createSequentialGroup()
                .addGroup(LoggedToolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoggedSearch)
                    .addComponent(LoggedHashButton)
                    .addComponent(LogOutButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ToolBarPanel.add(LoggedToolbarPanel, "card3");

        MainPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MainPane.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setText("Welcome to Not-Twitter!");

        jLabel2.setText("Click Log In or Register to access your account");

        jLabel3.setText("or just search for someone or something");

        javax.swing.GroupLayout MainPagePanelLayout = new javax.swing.GroupLayout(MainPagePanel);
        MainPagePanel.setLayout(MainPagePanelLayout);
        MainPagePanelLayout.setHorizontalGroup(
            MainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPagePanelLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(MainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        MainPagePanelLayout.setVerticalGroup(
            MainPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPagePanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        MainPane.add(MainPagePanel, "card2");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel4.setText("Start an Account");

        jLabel5.setText("Username");

        jLabel6.setText("Password");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");

        SignUpButton.setText("Start!");

        javax.swing.GroupLayout RegPagePanelLayout = new javax.swing.GroupLayout(RegPagePanel);
        RegPagePanel.setLayout(RegPagePanelLayout);
        RegPagePanelLayout.setHorizontalGroup(
            RegPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegPagePanelLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(RegPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RegPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addGroup(RegPagePanelLayout.createSequentialGroup()
                            .addGroup(RegPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(RegPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3)
                                .addComponent(jTextField4))))
                    .addComponent(SignUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        RegPagePanelLayout.setVerticalGroup(
            RegPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegPagePanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUpButton)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        MainPane.add(RegPagePanel, "card3");

        javax.swing.GroupLayout MyPagePanelLayout = new javax.swing.GroupLayout(MyPagePanel);
        MyPagePanel.setLayout(MyPagePanelLayout);
        MyPagePanelLayout.setHorizontalGroup(
            MyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        MyPagePanelLayout.setVerticalGroup(
            MyPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        MainPane.add(MyPagePanel, "card4");

        javax.swing.GroupLayout SearchResultsPanelLayout = new javax.swing.GroupLayout(SearchResultsPanel);
        SearchResultsPanel.setLayout(SearchResultsPanelLayout);
        SearchResultsPanelLayout.setHorizontalGroup(
            SearchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        SearchResultsPanelLayout.setVerticalGroup(
            SearchResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        MainPane.add(SearchResultsPanel, "card5");

        javax.swing.GroupLayout HashResultsPanelLayout = new javax.swing.GroupLayout(HashResultsPanel);
        HashResultsPanel.setLayout(HashResultsPanelLayout);
        HashResultsPanelLayout.setHorizontalGroup(
            HashResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
        );
        HashResultsPanelLayout.setVerticalGroup(
            HashResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        MainPane.add(HashResultsPanel, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ToolBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ToolBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 23, Short.MAX_VALUE)
                .addComponent(MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(MainPane.getLayout());
        cl.show(MainPane,"card3");
    }//GEN-LAST:event_RegisterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HashResultsPanel;
    private javax.swing.JButton LogInButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton LoggedHashButton;
    private javax.swing.JButton LoggedSearch;
    private javax.swing.JPanel LoggedToolbarPanel;
    private javax.swing.JPanel MainPagePanel;
    private javax.swing.JPanel MainPane;
    private javax.swing.JPanel MyPagePanel;
    private javax.swing.JPanel RegPagePanel;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JPanel SearchResultsPanel;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JPanel ToolBarPanel;
    private javax.swing.JButton UnloggedHashButton;
    private javax.swing.JButton UnloggedSearchButton;
    private javax.swing.JPanel UnloggedToolbarPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
