DROP DATABASE IF EXISTS SocialNetwork;
CREATE DATABASE SocialNetwork;
GRANT ALL PRIVILEGES ON SocialNetwork.* to 'assist'@'localhost' identified by 'assist';
USE SocialNetwork;
DROP TABLE IF EXISTS User;
CREATE TABLE User 
(
ID INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
User VARCHAR(30) NOT NULL DEFAULT '',
Pass VARCHAR(30) NOT NULL DEFAULT '',
Email VARCHAR(30) NOT NULL DEFAULT '',
Phone INT(10)
)